<Project Sdk="Microsoft.NET.Sdk.Web">

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <UserSecretsId>1fcaadfd-fd89-4dde-98d7-e2a689e2c887</UserSecretsId>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Supabase" Version="8.1.1" />
    <PackageReference Include="Swashbuckle.AspNetCore" Version="10.2.3" />
  </ItemGroup>

</Project>
